Implement concurrent pipeline
tamirOK/go-learn pull request #8
Opened 2023-02-27 18:54 UTC by tamirOK

2023-03-01 00:01 UTC, agneum requested changes

2023-03-01 00:01 UTC, agneum commented on pipeline/pipeline.go
> +		for v := range stage(in) {
Рекомендую убрать range: если в канале нет элементов, то пайплайн не получится остановить

Предложил бы не передавать stage внутрь wrapper и вызывать эту функцию в основном цикле

2023-03-01 00:01 UTC, agneum commented on pipeline/pipeline.go
> +	close(results)
Можно ли возвращать канал `in` без промежуточного слайса?

2023-03-02 17:28 UTC, tamirOK commented on pipeline/pipeline.go
> +	close(results)
Если я верну канал без промежуточного слайса и будет отмена, то тогда тест `require.Len(t, result, 0)` упадет.

Промежуточный слайс нужен, чтобы прочитать все значения из канала `in` перед его возвращением

2023-03-02 17:50 UTC, tamirOK commented on pipeline/pipeline.go
> +		for v := range stage(in) {
Поправил

2023-03-02 22:56 UTC, agneum approved these changes

2023-03-04 10:01 UTC, merged